- name: Setup DBSP machine
  hosts: all
  tasks:
    - name: Download Installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
    - name: install rust/cargo
      shell: /tmp/sh.rustup.rs -y
    - name: Clone the DBSP project
      ansible.builtin.git:
        repo: https://github.com/vmware/database-stream-processor.git
        dest: /home/ubuntu/database-stream-processor
        depth: 1
    - name: Copy the benchmark shell script
      ansible.builtin.copy:
        src: templates/dbsp-bench.sh
        dest: /home/ubuntu/
        mode: 0755
    - name: Install required DBSP (or deps) build packages
      ansible.builtin.apt:
        pkg:
        - build-essential
        - libssl-dev
        - pkg-config
      become: yes
